
date:
    start: 2018-2-28 00:00:00
    stop:  2018-3-10 00:00:00

run_name: 'latest'

region:
    bbox: [-71.20, 41.40, -69.20, 43.74]
    crs: 'urn:ogc:def:crs:OGC:1.3:CRS84'

# try: sea_surface_wave_significant_height
sos_name: 'waves'

cf_names:
    - sea_surface_wave_significant_height
    - sea_surface_wind_wave_significant_height

units: 'm'

catalogs:
    - https://data.ioos.us/csw
